Repository Aymanhki/Epoch, pull requests merged in 2024-02, with the labels that each got.

#12 Login and Register user stories complete
  Block Diagram.docx
  Project Tree.md
  epoch_backend/assets/epoch_db.sql
  epoch_backend/business/api_endpoints/router.py
  epoch_backend/business/api_endpoints/user_endpoints.py
  epoch_backend/business/db_controller/access_media_persistence.py
  epoch_backend/business/db_controller/access_session_persistence.py
  epoch_backend/business/db_controller/access_user_persistence.py
  epoch_backend/business/services.py
  epoch_backend/business/utils.py
  epoch_backend/business/webserver.py
  epoch_backend/main.py
  epoch_backend/objects/media.py
  epoch_backend/objects/session.py
  epoch_backend/objects/user.py
  epoch_backend/persistence/epoch/epoch_media_persistence.py
  epoch_backend/persistence/epoch/epoch_session_persistence.py
  epoch_backend/persistence/epoch/epoch_user_persistence.py
  epoch_backend/persistence/interfaces/media_persistence.py
  epoch_backend/persistence/interfaces/session_persistence.py
  epoch_backend/persistence/interfaces/user_persistence.py
  epoch_frontend/public/images/default_pfp.png
  epoch_frontend/src/modules/Router.js
  epoch_frontend/src/pages/home.js
  epoch_frontend/src/pages/login.js
  epoch_frontend/src/pages/profile.js
  epoch_frontend/src/pages/register.js
  epoch_frontend/src/services/user.js
  epoch_frontend/src/styles/Login.css
  epoch_frontend/src/styles/Register.css
Labels: User Story

#133 Created the navigation bar.
  epoch_frontend/package-lock.json
  epoch_frontend/package.json
  epoch_frontend/src/modules/NavBar.js
  epoch_frontend/src/pages/home.js
  epoch_frontend/src/styles/NavBar.css
Labels: Dev Task

#145 Profile page, feed, posting, and username routing, and more
  epoch_backend/assets/epoch_db.sql
  epoch_backend/business/api_endpoints/post_endpoints.py
  epoch_backend/business/api_endpoints/router.py
  epoch_backend/business/api_endpoints/user_endpoints.py
  epoch_backend/business/db_controller/access_post_persistence.py
  epoch_backend/business/services.py
  epoch_backend/business/utils.py
  epoch_backend/business/webserver.py
  epoch_backend/objects/post.py
  epoch_backend/persistence/epoch/epoch_post_persistence.py
  epoch_backend/persistence/interfaces/post_persistence.py
  epoch_backend/tests/integration_tests.py
  epoch_backend/tests/webserver_tests.py
  epoch_frontend/package-lock.json
  epoch_frontend/package.json
  epoch_frontend/src/__tests__/mock.render.tests.js
  epoch_frontend/src/modules/Feed.js
  epoch_frontend/src/modules/NavBar.js
  epoch_frontend/src/modules/Post.js
  epoch_frontend/src/modules/PostPopup.js
  epoch_frontend/src/modules/SmartMedia.js
  epoch_frontend/src/pages/home.js
  epoch_frontend/src/pages/profile.js
  epoch_frontend/src/services/post.js
  epoch_frontend/src/services/user.js
  epoch_frontend/src/styles/Feed.css
  epoch_frontend/src/styles/Home.css
  epoch_frontend/src/styles/Post.css
  epoch_frontend/src/styles/PostPopup.css
  epoch_frontend/src/styles/Profile.css
Labels: User Story, Dev Task

#181 Added the favorites page and the ability to favorite posts
  epoch_backend/assets/epoch_db.sql
  epoch_backend/business/api_endpoints/post_endpoints.py
  epoch_backend/business/api_endpoints/router.py
  epoch_backend/business/db_controller/access_post_persistence.py
  epoch_backend/business/utils.py
  epoch_backend/persistence/epoch/epoch_post_persistence.py
  epoch_backend/persistence/interfaces/post_persistence.py
  epoch_frontend/src/modules/Feed.js
  epoch_frontend/src/modules/Post.js
  epoch_frontend/src/modules/Router.js
  epoch_frontend/src/pages/Favorites.js
  epoch_frontend/src/pages/Hashtag.js
  epoch_frontend/src/pages/home.js
  epoch_frontend/src/pages/profile.js
  epoch_frontend/src/services/post.js
  epoch_frontend/src/styles/Favorites.css
  epoch_frontend/src/styles/Post.css
  epoch_frontend/src/styles/Profile.css
Labels: User Story, Dev Task

#187 Added sequence diagrams and testing plan as well as fixed a couple of bugs
  COMP 4350 - Winter 2024 - Testing Plan.docx
  COMP 4350 - Winter 2024 - Testing Plan.pdf
  Favourite Post Prediction Sequence Diagram.pdf
  Following-Followers Sequence Diagram.pdf
  Hashtag Posts Sequence Diagram.docx
  Hashtag Posts Sequence Diagram.pdf
  Post Prediction Sequence Diagram.pdf
  Register User Sequence Diagram.pdf
  epoch_frontend/src/pages/home.js
  epoch_frontend/src/pages/profile.js
  epoch_frontend/src/pages/userlist.js
Labels: bug
